backend:
  name: github
  repo: intsamdu/intsamdu.github.io
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "professors"
    label: "Professors"
    folder: "_people"
    create: true
    fields:
      - { label: "Name", name: "title", widget: "string" }
      - { label: "Position", name: "position", widget: "string" }
      - { label: "Bio", name: "body", widget: "markdown" }
